#!/usr/bin/env node
// Launches an isolated Firefox on a reusable, temporary/throwaway profile.
//
// Cross-platform (macOS/Linux/Windows), designed to be runnable directly or via `mise run firefox`.
//
// Example Usage:
//   node scripts/firefox.mjs # nightly, nova on
//   node scripts/firefox.mjs --channel beta # beta, nova off (channel default)
//   node scripts/firefox.mjs --nova off # override nova
//   node scripts/firefox.mjs --prefs josh # overlay scripts/user_profiles/josh.js
//   node scripts/firefox.mjs --remote # Marionette
//
// The profile is at tmp/profiles/<channel> . chrome/ is symlinked into here, as Firefox reads <profile>/chrome/userChrome.css,
// and user.js is regenerated every launch from scripts/user_profiles/base.js + any --prefs overlays, then browser.nova.enabled
// and the Marionette port are applied last.
//
// This is to allow nicer testing of the myriad of options both Firefox and material-fox-updated has, and allows testing cross-browser.
//
// `--remote` enables Marionette (port :2828) + the Remote Agent (WebDriver Classic + BiDi, :9222).
// Off by default, as marionette sets `navigator.webdriver` as `true`. This causes issues when using Google etc,
// as the browser tells the website, and they now think you're running a headless scraper or something...
// .... which is dumb, as there are so many workarounds, and Playwright for example just patches this out..

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
    CHANNELS,
    NOVA_DEFAULT,
    REPO,
    findBinary,
} from "./lib/firefox-bin.mjs";
import { linkChrome } from "./lib/profile.mjs";

function parseArgs(argv) {
    const args = { prefs: [], rest: [] };
    for (let i = 0; i < argv.length; i++) {
        const t = argv[i];
        switch (t) {
            case "--channel":
                args.channel = argv[++i];
                break;
            case "--nova":
                args.nova = argv[++i];
                break;
            case "--prefs":
                args.prefs.push(
                    ...String(argv[++i] ?? "")
                        .split(",")
                        .map((s) => s.trim())
                        .filter(Boolean),
                );
                break;
            case "--profile":
                args.profile = argv[++i];
                break;
            case "--remote":
                args.remote = true;
                break;
            case "--":
                args.rest.push(...argv.slice(i + 1));
                i = argv.length;
                break;
            default:
                args.rest.push(t);
        }
    }
    return args;
}

const die = (msg) => {
    console.error(`error: ${msg}`);
    process.exit(1);
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Render a JS prefs object to user.js lines. Later keys override earlier ones.
function renderUserJs(prefs) {
    const line = ([k, v]) =>
        `user_pref(${JSON.stringify(k)}, ${JSON.stringify(v)});`;
    return [
        "// Generated by scripts/firefox.mjs -- regenerated on every launch, do not edit.",
        ...Object.entries(prefs).map(line),
        "",
    ].join("\n");
}

async function loadOverlay(name) {
    const file = join(REPO, "scripts", "user_profiles", `${name}.js`);
    if (!existsSync(file)) die(`no pref overlay "${name}" at ${file}`);
    const mod = await import(pathToFileURL(file).href);
    return mod.default ?? {};
}

async function main() {
    const args = parseArgs(process.argv.slice(2));
    const channel = args.channel ?? "nightly";
    if (!CHANNELS.includes(channel))
        die(`invalid channel: ${channel} (expected ${CHANNELS.join("|")})`);

    let nova = NOVA_DEFAULT[channel];
    if (args.nova === "on") nova = true;
    else if (args.nova === "off") nova = false;
    else if (args.nova) die(`--nova expects on|off, got "${args.nova}"`);

    // Auto-provision the channel build so `mise run firefox` works from a clean checkout.
    let binary = findBinary(channel);
    if (!binary) {
        console.error(
            `No ${channel} build under tmp/firefox -- running download-firefox ...`,
        );
        const dl = spawnSync(
            process.execPath,
            [
                join(REPO, "scripts", "download-firefox.mjs"),
                "--channel",
                channel,
            ],
            { stdio: "inherit" },
        );
        if (dl.status !== 0) die(`download-firefox failed for ${channel}`);
        binary = findBinary(channel);
    }
    if (!binary)
        die(
            `no ${channel} binary after download-firefox (check the output above)`,
        );

    const profileDir = args.profile ?? join(REPO, "tmp", "profiles", channel);
    mkdirSync(join(profileDir, "extensions"), { recursive: true });
    linkChrome(profileDir);

    // base + overlays + computed (nova / marionette) last.
    let prefs = (
        await import(
            pathToFileURL(join(REPO, "scripts", "user_profiles", "base.js"))
                .href
        )
    ).default;
    for (const name of args.prefs)
        prefs = { ...prefs, ...(await loadOverlay(name)) };
    prefs = { ...prefs, "browser.nova.enabled": nova };
    writeFileSync(join(profileDir, "user.js"), renderUserJs(prefs));

    const overlayNote = args.prefs.length
        ? `  prefs: base + ${args.prefs.join(", ")}`
        : "  prefs: base";
    console.error(
        `Firefox ${channel}  (nova=${nova})\n  binary:  ${binary}\n  profile: ${profileDir}\n${overlayNote}`,
    );

    const ffArgs = ["--profile", profileDir, "--new-instance"];
    if (args.remote) {
        console.error(
            "Remote debugging ON (Marionette :2828, BiDi :9222), navigator.webdriver=true, expect CAPTCHAs.",
        );
        ffArgs.push("--marionette", "--remote-debugging-port=9222");
    }
    if (process.platform === "win32" && process.stdout.isTTY) {
        // -attach-console routes Firefox's stdout/stderr to the parent console so its
        // logs stream (like the inherited stdio on macOS/Linux). It hard-fails the
        // launch when there is no real console to attach to (piped/redirected stdout, mise capturing output, or a non-interactive SSH session),
        // so we check TTY.
        // `mise run firefox` is marked raw (mise.toml) so an interactive console reaches here instead of a pipe.
        ffArgs.push("-attach-console");
    }
    ffArgs.push(...args.rest);

    if (process.platform === "win32") {
        await launchAndSuperviseWindows(binary, ffArgs, profileDir);
        return;
    }

    const res = spawnSync(binary, ffArgs, { stdio: "inherit" });
    if (res.error) die(res.error.message);
    process.exit(res.status ?? 0);
}

// Windows. Fk me.
// firefox.exe is a launcher stub that spawns the real browser and returns in ~100ms.
// the launcher's own -wait-for-browser only blocks on certain elevation paths, so it is
// not reliable. To match the foreground behaviour elsewhere, task stays alive, Ctrl+C closes Firefox, we can
// snapshot the running firefox.exe PIDs, launch, then block until the PIDs that appeared afterwards have all exited.
// Massive fkn workaround? Yes. Do I hate myself? Yes. But this works well.
// Ctrl+C kills them first.
// PID-diff via tasklist needs no elevated CommandLine access (which is hidden over a non-interactive SSH session), so it works both in an interactive console and remotely.
async function launchAndSuperviseWindows(binary, ffArgs, profileDir) {
    const listPids = () => {
        const r = spawnSync(
            "tasklist",
            ["/fi", "imagename eq firefox.exe", "/nh", "/fo", "csv"],
            { encoding: "utf8" },
        );
        const pids = [];
        for (const line of (r.stdout || "").split(/\r?\n/)) {
            const m = line.match(/^"firefox\.exe","(\d+)"/i);
            if (m) pids.push(m[1]);
        }
        return pids;
    };

    const before = new Set(listPids());
    const start = spawnSync(binary, ffArgs, { stdio: "inherit" });
    if (start.error) die(start.error.message);
    // PIDs that were not running before this launch -- our browser + its children.
    const ours = () => listPids().filter((p) => !before.has(p));

    let shuttingDown = false;
    const shutdown = () => {
        if (shuttingDown) return;
        shuttingDown = true;
        for (const pid of ours())
            spawnSync("taskkill", ["/f", "/t", "/pid", pid], {
                stdio: "ignore",
            });
        process.exit(130);
    };
    process.on("SIGINT", shutdown);
    process.on("SIGTERM", shutdown);

    // Wait for the browser to come up (~15s grace), then block until it exits.
    const appearBy = Date.now() + 15000;
    while (Date.now() < appearBy && ours().length === 0) await sleep(500);
    while (ours().length > 0) await sleep(1500);
    process.exit(0);
}

main();
